name: Publish GH copy
on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write

jobs:
  archive_job:
    name: Archive 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'
    - name: WASM target
      shell: bash
      run: GOOS=js GOARCH=wasm go generate
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ebiten-ghpages
        retention-days: 1
        path: |
          dist/web/
          LICENSE

  publish_job:
    needs: archive_job
    if: github.ref == 'refs/heads/main'
    name: Pub to GH pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: ebiten-ghpages

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: gh-pages
        folder: dist/web
